// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kriuchkov/jiraforge/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewJiraService creates a new instance of JiraService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJiraService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JiraService {
	mock := &JiraService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JiraService is an autogenerated mock type for the JiraService type
type JiraService struct {
	mock.Mock
}

type JiraService_Expecter struct {
	mock *mock.Mock
}

func (_m *JiraService) EXPECT() *JiraService_Expecter {
	return &JiraService_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function for the type JiraService
func (_mock *JiraService) AddComment(context1 context.Context, addCommentRequest models.AddCommentRequest) (*models.Comment, error) {
	ret := _mock.Called(context1, addCommentRequest)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 *models.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AddCommentRequest) (*models.Comment, error)); ok {
		return returnFunc(context1, addCommentRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AddCommentRequest) *models.Comment); ok {
		r0 = returnFunc(context1, addCommentRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.AddCommentRequest) error); ok {
		r1 = returnFunc(context1, addCommentRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type JiraService_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - context1 context.Context
//   - addCommentRequest models.AddCommentRequest
func (_e *JiraService_Expecter) AddComment(context1 interface{}, addCommentRequest interface{}) *JiraService_AddComment_Call {
	return &JiraService_AddComment_Call{Call: _e.mock.On("AddComment", context1, addCommentRequest)}
}

func (_c *JiraService_AddComment_Call) Run(run func(context1 context.Context, addCommentRequest models.AddCommentRequest)) *JiraService_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.AddCommentRequest
		if args[1] != nil {
			arg1 = args[1].(models.AddCommentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_AddComment_Call) Return(comment *models.Comment, err error) *JiraService_AddComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *JiraService_AddComment_Call) RunAndReturn(run func(context1 context.Context, addCommentRequest models.AddCommentRequest) (*models.Comment, error)) *JiraService_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// AddWorklog provides a mock function for the type JiraService
func (_mock *JiraService) AddWorklog(context1 context.Context, addWorklogRequest models.AddWorklogRequest) (*models.Worklog, error) {
	ret := _mock.Called(context1, addWorklogRequest)

	if len(ret) == 0 {
		panic("no return value specified for AddWorklog")
	}

	var r0 *models.Worklog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AddWorklogRequest) (*models.Worklog, error)); ok {
		return returnFunc(context1, addWorklogRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AddWorklogRequest) *models.Worklog); ok {
		r0 = returnFunc(context1, addWorklogRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Worklog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.AddWorklogRequest) error); ok {
		r1 = returnFunc(context1, addWorklogRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_AddWorklog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorklog'
type JiraService_AddWorklog_Call struct {
	*mock.Call
}

// AddWorklog is a helper method to define mock.On call
//   - context1 context.Context
//   - addWorklogRequest models.AddWorklogRequest
func (_e *JiraService_Expecter) AddWorklog(context1 interface{}, addWorklogRequest interface{}) *JiraService_AddWorklog_Call {
	return &JiraService_AddWorklog_Call{Call: _e.mock.On("AddWorklog", context1, addWorklogRequest)}
}

func (_c *JiraService_AddWorklog_Call) Run(run func(context1 context.Context, addWorklogRequest models.AddWorklogRequest)) *JiraService_AddWorklog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.AddWorklogRequest
		if args[1] != nil {
			arg1 = args[1].(models.AddWorklogRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_AddWorklog_Call) Return(worklog *models.Worklog, err error) *JiraService_AddWorklog_Call {
	_c.Call.Return(worklog, err)
	return _c
}

func (_c *JiraService_AddWorklog_Call) RunAndReturn(run func(context1 context.Context, addWorklogRequest models.AddWorklogRequest) (*models.Worklog, error)) *JiraService_AddWorklog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChildIssue provides a mock function for the type JiraService
func (_mock *JiraService) CreateChildIssue(context1 context.Context, createChildIssueRequest models.CreateChildIssueRequest) (*models.IssueMutationResult, error) {
	ret := _mock.Called(context1, createChildIssueRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateChildIssue")
	}

	var r0 *models.IssueMutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateChildIssueRequest) (*models.IssueMutationResult, error)); ok {
		return returnFunc(context1, createChildIssueRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateChildIssueRequest) *models.IssueMutationResult); ok {
		r0 = returnFunc(context1, createChildIssueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueMutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.CreateChildIssueRequest) error); ok {
		r1 = returnFunc(context1, createChildIssueRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_CreateChildIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChildIssue'
type JiraService_CreateChildIssue_Call struct {
	*mock.Call
}

// CreateChildIssue is a helper method to define mock.On call
//   - context1 context.Context
//   - createChildIssueRequest models.CreateChildIssueRequest
func (_e *JiraService_Expecter) CreateChildIssue(context1 interface{}, createChildIssueRequest interface{}) *JiraService_CreateChildIssue_Call {
	return &JiraService_CreateChildIssue_Call{Call: _e.mock.On("CreateChildIssue", context1, createChildIssueRequest)}
}

func (_c *JiraService_CreateChildIssue_Call) Run(run func(context1 context.Context, createChildIssueRequest models.CreateChildIssueRequest)) *JiraService_CreateChildIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.CreateChildIssueRequest
		if args[1] != nil {
			arg1 = args[1].(models.CreateChildIssueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_CreateChildIssue_Call) Return(issueMutationResult *models.IssueMutationResult, err error) *JiraService_CreateChildIssue_Call {
	_c.Call.Return(issueMutationResult, err)
	return _c
}

func (_c *JiraService_CreateChildIssue_Call) RunAndReturn(run func(context1 context.Context, createChildIssueRequest models.CreateChildIssueRequest) (*models.IssueMutationResult, error)) *JiraService_CreateChildIssue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssue provides a mock function for the type JiraService
func (_mock *JiraService) CreateIssue(context1 context.Context, createIssueRequest models.CreateIssueRequest) (*models.IssueMutationResult, error) {
	ret := _mock.Called(context1, createIssueRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssue")
	}

	var r0 *models.IssueMutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateIssueRequest) (*models.IssueMutationResult, error)); ok {
		return returnFunc(context1, createIssueRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateIssueRequest) *models.IssueMutationResult); ok {
		r0 = returnFunc(context1, createIssueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueMutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.CreateIssueRequest) error); ok {
		r1 = returnFunc(context1, createIssueRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_CreateIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssue'
type JiraService_CreateIssue_Call struct {
	*mock.Call
}

// CreateIssue is a helper method to define mock.On call
//   - context1 context.Context
//   - createIssueRequest models.CreateIssueRequest
func (_e *JiraService_Expecter) CreateIssue(context1 interface{}, createIssueRequest interface{}) *JiraService_CreateIssue_Call {
	return &JiraService_CreateIssue_Call{Call: _e.mock.On("CreateIssue", context1, createIssueRequest)}
}

func (_c *JiraService_CreateIssue_Call) Run(run func(context1 context.Context, createIssueRequest models.CreateIssueRequest)) *JiraService_CreateIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.CreateIssueRequest
		if args[1] != nil {
			arg1 = args[1].(models.CreateIssueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_CreateIssue_Call) Return(issueMutationResult *models.IssueMutationResult, err error) *JiraService_CreateIssue_Call {
	_c.Call.Return(issueMutationResult, err)
	return _c
}

func (_c *JiraService_CreateIssue_Call) RunAndReturn(run func(context1 context.Context, createIssueRequest models.CreateIssueRequest) (*models.IssueMutationResult, error)) *JiraService_CreateIssue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssue provides a mock function for the type JiraService
func (_mock *JiraService) DeleteIssue(context1 context.Context, deleteIssueRequest models.DeleteIssueRequest) (*models.IssueMutationResult, error) {
	ret := _mock.Called(context1, deleteIssueRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssue")
	}

	var r0 *models.IssueMutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeleteIssueRequest) (*models.IssueMutationResult, error)); ok {
		return returnFunc(context1, deleteIssueRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeleteIssueRequest) *models.IssueMutationResult); ok {
		r0 = returnFunc(context1, deleteIssueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueMutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.DeleteIssueRequest) error); ok {
		r1 = returnFunc(context1, deleteIssueRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_DeleteIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssue'
type JiraService_DeleteIssue_Call struct {
	*mock.Call
}

// DeleteIssue is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteIssueRequest models.DeleteIssueRequest
func (_e *JiraService_Expecter) DeleteIssue(context1 interface{}, deleteIssueRequest interface{}) *JiraService_DeleteIssue_Call {
	return &JiraService_DeleteIssue_Call{Call: _e.mock.On("DeleteIssue", context1, deleteIssueRequest)}
}

func (_c *JiraService_DeleteIssue_Call) Run(run func(context1 context.Context, deleteIssueRequest models.DeleteIssueRequest)) *JiraService_DeleteIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DeleteIssueRequest
		if args[1] != nil {
			arg1 = args[1].(models.DeleteIssueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_DeleteIssue_Call) Return(issueMutationResult *models.IssueMutationResult, err error) *JiraService_DeleteIssue_Call {
	_c.Call.Return(issueMutationResult, err)
	return _c
}

func (_c *JiraService_DeleteIssue_Call) RunAndReturn(run func(context1 context.Context, deleteIssueRequest models.DeleteIssueRequest) (*models.IssueMutationResult, error)) *JiraService_DeleteIssue_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadAttachment provides a mock function for the type JiraService
func (_mock *JiraService) DownloadAttachment(context1 context.Context, downloadAttachmentRequest models.DownloadAttachmentRequest) (*models.StoredAttachment, error) {
	ret := _mock.Called(context1, downloadAttachmentRequest)

	if len(ret) == 0 {
		panic("no return value specified for DownloadAttachment")
	}

	var r0 *models.StoredAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DownloadAttachmentRequest) (*models.StoredAttachment, error)); ok {
		return returnFunc(context1, downloadAttachmentRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DownloadAttachmentRequest) *models.StoredAttachment); ok {
		r0 = returnFunc(context1, downloadAttachmentRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StoredAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.DownloadAttachmentRequest) error); ok {
		r1 = returnFunc(context1, downloadAttachmentRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_DownloadAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAttachment'
type JiraService_DownloadAttachment_Call struct {
	*mock.Call
}

// DownloadAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - downloadAttachmentRequest models.DownloadAttachmentRequest
func (_e *JiraService_Expecter) DownloadAttachment(context1 interface{}, downloadAttachmentRequest interface{}) *JiraService_DownloadAttachment_Call {
	return &JiraService_DownloadAttachment_Call{Call: _e.mock.On("DownloadAttachment", context1, downloadAttachmentRequest)}
}

func (_c *JiraService_DownloadAttachment_Call) Run(run func(context1 context.Context, downloadAttachmentRequest models.DownloadAttachmentRequest)) *JiraService_DownloadAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DownloadAttachmentRequest
		if args[1] != nil {
			arg1 = args[1].(models.DownloadAttachmentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_DownloadAttachment_Call) Return(storedAttachment *models.StoredAttachment, err error) *JiraService_DownloadAttachment_Call {
	_c.Call.Return(storedAttachment, err)
	return _c
}

func (_c *JiraService_DownloadAttachment_Call) RunAndReturn(run func(context1 context.Context, downloadAttachmentRequest models.DownloadAttachmentRequest) (*models.StoredAttachment, error)) *JiraService_DownloadAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSprint provides a mock function for the type JiraService
func (_mock *JiraService) GetActiveSprint(context1 context.Context, getActiveSprintRequest models.GetActiveSprintRequest) (*models.Sprint, error) {
	ret := _mock.Called(context1, getActiveSprintRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSprint")
	}

	var r0 *models.Sprint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetActiveSprintRequest) (*models.Sprint, error)); ok {
		return returnFunc(context1, getActiveSprintRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetActiveSprintRequest) *models.Sprint); ok {
		r0 = returnFunc(context1, getActiveSprintRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Sprint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetActiveSprintRequest) error); ok {
		r1 = returnFunc(context1, getActiveSprintRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetActiveSprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSprint'
type JiraService_GetActiveSprint_Call struct {
	*mock.Call
}

// GetActiveSprint is a helper method to define mock.On call
//   - context1 context.Context
//   - getActiveSprintRequest models.GetActiveSprintRequest
func (_e *JiraService_Expecter) GetActiveSprint(context1 interface{}, getActiveSprintRequest interface{}) *JiraService_GetActiveSprint_Call {
	return &JiraService_GetActiveSprint_Call{Call: _e.mock.On("GetActiveSprint", context1, getActiveSprintRequest)}
}

func (_c *JiraService_GetActiveSprint_Call) Run(run func(context1 context.Context, getActiveSprintRequest models.GetActiveSprintRequest)) *JiraService_GetActiveSprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetActiveSprintRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetActiveSprintRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetActiveSprint_Call) Return(sprint *models.Sprint, err error) *JiraService_GetActiveSprint_Call {
	_c.Call.Return(sprint, err)
	return _c
}

func (_c *JiraService_GetActiveSprint_Call) RunAndReturn(run func(context1 context.Context, getActiveSprintRequest models.GetActiveSprintRequest) (*models.Sprint, error)) *JiraService_GetActiveSprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgingReport provides a mock function for the type JiraService
func (_mock *JiraService) GetAgingReport(context1 context.Context, getAgingReportRequest models.GetAgingReportRequest) (*models.AgingReport, error) {
	ret := _mock.Called(context1, getAgingReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetAgingReport")
	}

	var r0 *models.AgingReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetAgingReportRequest) (*models.AgingReport, error)); ok {
		return returnFunc(context1, getAgingReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetAgingReportRequest) *models.AgingReport); ok {
		r0 = returnFunc(context1, getAgingReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgingReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetAgingReportRequest) error); ok {
		r1 = returnFunc(context1, getAgingReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetAgingReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgingReport'
type JiraService_GetAgingReport_Call struct {
	*mock.Call
}

// GetAgingReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getAgingReportRequest models.GetAgingReportRequest
func (_e *JiraService_Expecter) GetAgingReport(context1 interface{}, getAgingReportRequest interface{}) *JiraService_GetAgingReport_Call {
	return &JiraService_GetAgingReport_Call{Call: _e.mock.On("GetAgingReport", context1, getAgingReportRequest)}
}

func (_c *JiraService_GetAgingReport_Call) Run(run func(context1 context.Context, getAgingReportRequest models.GetAgingReportRequest)) *JiraService_GetAgingReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetAgingReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetAgingReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetAgingReport_Call) Return(agingReport *models.AgingReport, err error) *JiraService_GetAgingReport_Call {
	_c.Call.Return(agingReport, err)
	return _c
}

func (_c *JiraService_GetAgingReport_Call) RunAndReturn(run func(context1 context.Context, getAgingReportRequest models.GetAgingReportRequest) (*models.AgingReport, error)) *JiraService_GetAgingReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedIssuesReport provides a mock function for the type JiraService
func (_mock *JiraService) GetBlockedIssuesReport(context1 context.Context, getBlockedIssuesReportRequest models.GetBlockedIssuesReportRequest) (*models.BlockedIssuesReport, error) {
	ret := _mock.Called(context1, getBlockedIssuesReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedIssuesReport")
	}

	var r0 *models.BlockedIssuesReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetBlockedIssuesReportRequest) (*models.BlockedIssuesReport, error)); ok {
		return returnFunc(context1, getBlockedIssuesReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetBlockedIssuesReportRequest) *models.BlockedIssuesReport); ok {
		r0 = returnFunc(context1, getBlockedIssuesReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BlockedIssuesReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetBlockedIssuesReportRequest) error); ok {
		r1 = returnFunc(context1, getBlockedIssuesReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetBlockedIssuesReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedIssuesReport'
type JiraService_GetBlockedIssuesReport_Call struct {
	*mock.Call
}

// GetBlockedIssuesReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getBlockedIssuesReportRequest models.GetBlockedIssuesReportRequest
func (_e *JiraService_Expecter) GetBlockedIssuesReport(context1 interface{}, getBlockedIssuesReportRequest interface{}) *JiraService_GetBlockedIssuesReport_Call {
	return &JiraService_GetBlockedIssuesReport_Call{Call: _e.mock.On("GetBlockedIssuesReport", context1, getBlockedIssuesReportRequest)}
}

func (_c *JiraService_GetBlockedIssuesReport_Call) Run(run func(context1 context.Context, getBlockedIssuesReportRequest models.GetBlockedIssuesReportRequest)) *JiraService_GetBlockedIssuesReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetBlockedIssuesReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetBlockedIssuesReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetBlockedIssuesReport_Call) Return(blockedIssuesReport *models.BlockedIssuesReport, err error) *JiraService_GetBlockedIssuesReport_Call {
	_c.Call.Return(blockedIssuesReport, err)
	return _c
}

func (_c *JiraService_GetBlockedIssuesReport_Call) RunAndReturn(run func(context1 context.Context, getBlockedIssuesReportRequest models.GetBlockedIssuesReportRequest) (*models.BlockedIssuesReport, error)) *JiraService_GetBlockedIssuesReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type JiraService
func (_mock *JiraService) GetComments(context1 context.Context, getCommentsRequest models.GetCommentsRequest) (*models.CommentList, error) {
	ret := _mock.Called(context1, getCommentsRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 *models.CommentList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetCommentsRequest) (*models.CommentList, error)); ok {
		return returnFunc(context1, getCommentsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetCommentsRequest) *models.CommentList); ok {
		r0 = returnFunc(context1, getCommentsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CommentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetCommentsRequest) error); ok {
		r1 = returnFunc(context1, getCommentsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type JiraService_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - context1 context.Context
//   - getCommentsRequest models.GetCommentsRequest
func (_e *JiraService_Expecter) GetComments(context1 interface{}, getCommentsRequest interface{}) *JiraService_GetComments_Call {
	return &JiraService_GetComments_Call{Call: _e.mock.On("GetComments", context1, getCommentsRequest)}
}

func (_c *JiraService_GetComments_Call) Run(run func(context1 context.Context, getCommentsRequest models.GetCommentsRequest)) *JiraService_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetCommentsRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetCommentsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetComments_Call) Return(commentList *models.CommentList, err error) *JiraService_GetComments_Call {
	_c.Call.Return(commentList, err)
	return _c
}

func (_c *JiraService_GetComments_Call) RunAndReturn(run func(context1 context.Context, getCommentsRequest models.GetCommentsRequest) (*models.CommentList, error)) *JiraService_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetCycleTimeReport provides a mock function for the type JiraService
func (_mock *JiraService) GetCycleTimeReport(context1 context.Context, getCycleTimeReportRequest models.GetCycleTimeReportRequest) (*models.CycleTimeReport, error) {
	ret := _mock.Called(context1, getCycleTimeReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetCycleTimeReport")
	}

	var r0 *models.CycleTimeReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetCycleTimeReportRequest) (*models.CycleTimeReport, error)); ok {
		return returnFunc(context1, getCycleTimeReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetCycleTimeReportRequest) *models.CycleTimeReport); ok {
		r0 = returnFunc(context1, getCycleTimeReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CycleTimeReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetCycleTimeReportRequest) error); ok {
		r1 = returnFunc(context1, getCycleTimeReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetCycleTimeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCycleTimeReport'
type JiraService_GetCycleTimeReport_Call struct {
	*mock.Call
}

// GetCycleTimeReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getCycleTimeReportRequest models.GetCycleTimeReportRequest
func (_e *JiraService_Expecter) GetCycleTimeReport(context1 interface{}, getCycleTimeReportRequest interface{}) *JiraService_GetCycleTimeReport_Call {
	return &JiraService_GetCycleTimeReport_Call{Call: _e.mock.On("GetCycleTimeReport", context1, getCycleTimeReportRequest)}
}

func (_c *JiraService_GetCycleTimeReport_Call) Run(run func(context1 context.Context, getCycleTimeReportRequest models.GetCycleTimeReportRequest)) *JiraService_GetCycleTimeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetCycleTimeReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetCycleTimeReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetCycleTimeReport_Call) Return(cycleTimeReport *models.CycleTimeReport, err error) *JiraService_GetCycleTimeReport_Call {
	_c.Call.Return(cycleTimeReport, err)
	return _c
}

func (_c *JiraService_GetCycleTimeReport_Call) RunAndReturn(run func(context1 context.Context, getCycleTimeReportRequest models.GetCycleTimeReportRequest) (*models.CycleTimeReport, error)) *JiraService_GetCycleTimeReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevelopmentInfo provides a mock function for the type JiraService
func (_mock *JiraService) GetDevelopmentInfo(context1 context.Context, getDevelopmentInfoRequest models.GetDevelopmentInfoRequest) (*models.DevelopmentInfo, error) {
	ret := _mock.Called(context1, getDevelopmentInfoRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetDevelopmentInfo")
	}

	var r0 *models.DevelopmentInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetDevelopmentInfoRequest) (*models.DevelopmentInfo, error)); ok {
		return returnFunc(context1, getDevelopmentInfoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetDevelopmentInfoRequest) *models.DevelopmentInfo); ok {
		r0 = returnFunc(context1, getDevelopmentInfoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DevelopmentInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetDevelopmentInfoRequest) error); ok {
		r1 = returnFunc(context1, getDevelopmentInfoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetDevelopmentInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevelopmentInfo'
type JiraService_GetDevelopmentInfo_Call struct {
	*mock.Call
}

// GetDevelopmentInfo is a helper method to define mock.On call
//   - context1 context.Context
//   - getDevelopmentInfoRequest models.GetDevelopmentInfoRequest
func (_e *JiraService_Expecter) GetDevelopmentInfo(context1 interface{}, getDevelopmentInfoRequest interface{}) *JiraService_GetDevelopmentInfo_Call {
	return &JiraService_GetDevelopmentInfo_Call{Call: _e.mock.On("GetDevelopmentInfo", context1, getDevelopmentInfoRequest)}
}

func (_c *JiraService_GetDevelopmentInfo_Call) Run(run func(context1 context.Context, getDevelopmentInfoRequest models.GetDevelopmentInfoRequest)) *JiraService_GetDevelopmentInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetDevelopmentInfoRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetDevelopmentInfoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetDevelopmentInfo_Call) Return(developmentInfo *models.DevelopmentInfo, err error) *JiraService_GetDevelopmentInfo_Call {
	_c.Call.Return(developmentInfo, err)
	return _c
}

func (_c *JiraService_GetDevelopmentInfo_Call) RunAndReturn(run func(context1 context.Context, getDevelopmentInfoRequest models.GetDevelopmentInfoRequest) (*models.DevelopmentInfo, error)) *JiraService_GetDevelopmentInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowEfficiencyReport provides a mock function for the type JiraService
func (_mock *JiraService) GetFlowEfficiencyReport(context1 context.Context, getFlowEfficiencyReportRequest models.GetFlowEfficiencyReportRequest) (*models.FlowEfficiencyReport, error) {
	ret := _mock.Called(context1, getFlowEfficiencyReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowEfficiencyReport")
	}

	var r0 *models.FlowEfficiencyReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetFlowEfficiencyReportRequest) (*models.FlowEfficiencyReport, error)); ok {
		return returnFunc(context1, getFlowEfficiencyReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetFlowEfficiencyReportRequest) *models.FlowEfficiencyReport); ok {
		r0 = returnFunc(context1, getFlowEfficiencyReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FlowEfficiencyReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetFlowEfficiencyReportRequest) error); ok {
		r1 = returnFunc(context1, getFlowEfficiencyReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetFlowEfficiencyReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowEfficiencyReport'
type JiraService_GetFlowEfficiencyReport_Call struct {
	*mock.Call
}

// GetFlowEfficiencyReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getFlowEfficiencyReportRequest models.GetFlowEfficiencyReportRequest
func (_e *JiraService_Expecter) GetFlowEfficiencyReport(context1 interface{}, getFlowEfficiencyReportRequest interface{}) *JiraService_GetFlowEfficiencyReport_Call {
	return &JiraService_GetFlowEfficiencyReport_Call{Call: _e.mock.On("GetFlowEfficiencyReport", context1, getFlowEfficiencyReportRequest)}
}

func (_c *JiraService_GetFlowEfficiencyReport_Call) Run(run func(context1 context.Context, getFlowEfficiencyReportRequest models.GetFlowEfficiencyReportRequest)) *JiraService_GetFlowEfficiencyReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetFlowEfficiencyReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetFlowEfficiencyReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetFlowEfficiencyReport_Call) Return(flowEfficiencyReport *models.FlowEfficiencyReport, err error) *JiraService_GetFlowEfficiencyReport_Call {
	_c.Call.Return(flowEfficiencyReport, err)
	return _c
}

func (_c *JiraService_GetFlowEfficiencyReport_Call) RunAndReturn(run func(context1 context.Context, getFlowEfficiencyReportRequest models.GetFlowEfficiencyReportRequest) (*models.FlowEfficiencyReport, error)) *JiraService_GetFlowEfficiencyReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssue provides a mock function for the type JiraService
func (_mock *JiraService) GetIssue(context1 context.Context, getIssueRequest models.GetIssueRequest) (*models.Issue, error) {
	ret := _mock.Called(context1, getIssueRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetIssue")
	}

	var r0 *models.Issue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetIssueRequest) (*models.Issue, error)); ok {
		return returnFunc(context1, getIssueRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetIssueRequest) *models.Issue); ok {
		r0 = returnFunc(context1, getIssueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Issue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetIssueRequest) error); ok {
		r1 = returnFunc(context1, getIssueRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssue'
type JiraService_GetIssue_Call struct {
	*mock.Call
}

// GetIssue is a helper method to define mock.On call
//   - context1 context.Context
//   - getIssueRequest models.GetIssueRequest
func (_e *JiraService_Expecter) GetIssue(context1 interface{}, getIssueRequest interface{}) *JiraService_GetIssue_Call {
	return &JiraService_GetIssue_Call{Call: _e.mock.On("GetIssue", context1, getIssueRequest)}
}

func (_c *JiraService_GetIssue_Call) Run(run func(context1 context.Context, getIssueRequest models.GetIssueRequest)) *JiraService_GetIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetIssueRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetIssueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetIssue_Call) Return(issue *models.Issue, err error) *JiraService_GetIssue_Call {
	_c.Call.Return(issue, err)
	return _c
}

func (_c *JiraService_GetIssue_Call) RunAndReturn(run func(context1 context.Context, getIssueRequest models.GetIssueRequest) (*models.Issue, error)) *JiraService_GetIssue_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssueHistory provides a mock function for the type JiraService
func (_mock *JiraService) GetIssueHistory(context1 context.Context, getIssueHistoryRequest models.GetIssueHistoryRequest) (*models.IssueHistory, error) {
	ret := _mock.Called(context1, getIssueHistoryRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueHistory")
	}

	var r0 *models.IssueHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetIssueHistoryRequest) (*models.IssueHistory, error)); ok {
		return returnFunc(context1, getIssueHistoryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetIssueHistoryRequest) *models.IssueHistory); ok {
		r0 = returnFunc(context1, getIssueHistoryRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetIssueHistoryRequest) error); ok {
		r1 = returnFunc(context1, getIssueHistoryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetIssueHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssueHistory'
type JiraService_GetIssueHistory_Call struct {
	*mock.Call
}

// GetIssueHistory is a helper method to define mock.On call
//   - context1 context.Context
//   - getIssueHistoryRequest models.GetIssueHistoryRequest
func (_e *JiraService_Expecter) GetIssueHistory(context1 interface{}, getIssueHistoryRequest interface{}) *JiraService_GetIssueHistory_Call {
	return &JiraService_GetIssueHistory_Call{Call: _e.mock.On("GetIssueHistory", context1, getIssueHistoryRequest)}
}

func (_c *JiraService_GetIssueHistory_Call) Run(run func(context1 context.Context, getIssueHistoryRequest models.GetIssueHistoryRequest)) *JiraService_GetIssueHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetIssueHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetIssueHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetIssueHistory_Call) Return(issueHistory *models.IssueHistory, err error) *JiraService_GetIssueHistory_Call {
	_c.Call.Return(issueHistory, err)
	return _c
}

func (_c *JiraService_GetIssueHistory_Call) RunAndReturn(run func(context1 context.Context, getIssueHistoryRequest models.GetIssueHistoryRequest) (*models.IssueHistory, error)) *JiraService_GetIssueHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelatedIssues provides a mock function for the type JiraService
func (_mock *JiraService) GetRelatedIssues(context1 context.Context, getRelatedIssuesRequest models.GetRelatedIssuesRequest) ([]models.IssueRelation, error) {
	ret := _mock.Called(context1, getRelatedIssuesRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetRelatedIssues")
	}

	var r0 []models.IssueRelation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetRelatedIssuesRequest) ([]models.IssueRelation, error)); ok {
		return returnFunc(context1, getRelatedIssuesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetRelatedIssuesRequest) []models.IssueRelation); ok {
		r0 = returnFunc(context1, getRelatedIssuesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IssueRelation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetRelatedIssuesRequest) error); ok {
		r1 = returnFunc(context1, getRelatedIssuesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetRelatedIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelatedIssues'
type JiraService_GetRelatedIssues_Call struct {
	*mock.Call
}

// GetRelatedIssues is a helper method to define mock.On call
//   - context1 context.Context
//   - getRelatedIssuesRequest models.GetRelatedIssuesRequest
func (_e *JiraService_Expecter) GetRelatedIssues(context1 interface{}, getRelatedIssuesRequest interface{}) *JiraService_GetRelatedIssues_Call {
	return &JiraService_GetRelatedIssues_Call{Call: _e.mock.On("GetRelatedIssues", context1, getRelatedIssuesRequest)}
}

func (_c *JiraService_GetRelatedIssues_Call) Run(run func(context1 context.Context, getRelatedIssuesRequest models.GetRelatedIssuesRequest)) *JiraService_GetRelatedIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetRelatedIssuesRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetRelatedIssuesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetRelatedIssues_Call) Return(issueRelations []models.IssueRelation, err error) *JiraService_GetRelatedIssues_Call {
	_c.Call.Return(issueRelations, err)
	return _c
}

func (_c *JiraService_GetRelatedIssues_Call) RunAndReturn(run func(context1 context.Context, getRelatedIssuesRequest models.GetRelatedIssuesRequest) ([]models.IssueRelation, error)) *JiraService_GetRelatedIssues_Call {
	_c.Call.Return(run)
	return _c
}

// GetSprint provides a mock function for the type JiraService
func (_mock *JiraService) GetSprint(context1 context.Context, getSprintRequest models.GetSprintRequest) (*models.Sprint, error) {
	ret := _mock.Called(context1, getSprintRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetSprint")
	}

	var r0 *models.Sprint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintRequest) (*models.Sprint, error)); ok {
		return returnFunc(context1, getSprintRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintRequest) *models.Sprint); ok {
		r0 = returnFunc(context1, getSprintRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Sprint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetSprintRequest) error); ok {
		r1 = returnFunc(context1, getSprintRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetSprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSprint'
type JiraService_GetSprint_Call struct {
	*mock.Call
}

// GetSprint is a helper method to define mock.On call
//   - context1 context.Context
//   - getSprintRequest models.GetSprintRequest
func (_e *JiraService_Expecter) GetSprint(context1 interface{}, getSprintRequest interface{}) *JiraService_GetSprint_Call {
	return &JiraService_GetSprint_Call{Call: _e.mock.On("GetSprint", context1, getSprintRequest)}
}

func (_c *JiraService_GetSprint_Call) Run(run func(context1 context.Context, getSprintRequest models.GetSprintRequest)) *JiraService_GetSprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetSprintRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetSprintRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetSprint_Call) Return(sprint *models.Sprint, err error) *JiraService_GetSprint_Call {
	_c.Call.Return(sprint, err)
	return _c
}

func (_c *JiraService_GetSprint_Call) RunAndReturn(run func(context1 context.Context, getSprintRequest models.GetSprintRequest) (*models.Sprint, error)) *JiraService_GetSprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetSprintHealthReport provides a mock function for the type JiraService
func (_mock *JiraService) GetSprintHealthReport(context1 context.Context, getSprintHealthReportRequest models.GetSprintHealthReportRequest) (*models.SprintHealthReport, error) {
	ret := _mock.Called(context1, getSprintHealthReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetSprintHealthReport")
	}

	var r0 *models.SprintHealthReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintHealthReportRequest) (*models.SprintHealthReport, error)); ok {
		return returnFunc(context1, getSprintHealthReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintHealthReportRequest) *models.SprintHealthReport); ok {
		r0 = returnFunc(context1, getSprintHealthReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SprintHealthReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetSprintHealthReportRequest) error); ok {
		r1 = returnFunc(context1, getSprintHealthReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetSprintHealthReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSprintHealthReport'
type JiraService_GetSprintHealthReport_Call struct {
	*mock.Call
}

// GetSprintHealthReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getSprintHealthReportRequest models.GetSprintHealthReportRequest
func (_e *JiraService_Expecter) GetSprintHealthReport(context1 interface{}, getSprintHealthReportRequest interface{}) *JiraService_GetSprintHealthReport_Call {
	return &JiraService_GetSprintHealthReport_Call{Call: _e.mock.On("GetSprintHealthReport", context1, getSprintHealthReportRequest)}
}

func (_c *JiraService_GetSprintHealthReport_Call) Run(run func(context1 context.Context, getSprintHealthReportRequest models.GetSprintHealthReportRequest)) *JiraService_GetSprintHealthReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetSprintHealthReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetSprintHealthReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetSprintHealthReport_Call) Return(sprintHealthReport *models.SprintHealthReport, err error) *JiraService_GetSprintHealthReport_Call {
	_c.Call.Return(sprintHealthReport, err)
	return _c
}

func (_c *JiraService_GetSprintHealthReport_Call) RunAndReturn(run func(context1 context.Context, getSprintHealthReportRequest models.GetSprintHealthReportRequest) (*models.SprintHealthReport, error)) *JiraService_GetSprintHealthReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetSprintReport provides a mock function for the type JiraService
func (_mock *JiraService) GetSprintReport(context1 context.Context, getSprintReportRequest models.GetSprintReportRequest) (*models.SprintReport, error) {
	ret := _mock.Called(context1, getSprintReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetSprintReport")
	}

	var r0 *models.SprintReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintReportRequest) (*models.SprintReport, error)); ok {
		return returnFunc(context1, getSprintReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintReportRequest) *models.SprintReport); ok {
		r0 = returnFunc(context1, getSprintReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SprintReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetSprintReportRequest) error); ok {
		r1 = returnFunc(context1, getSprintReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetSprintReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSprintReport'
type JiraService_GetSprintReport_Call struct {
	*mock.Call
}

// GetSprintReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getSprintReportRequest models.GetSprintReportRequest
func (_e *JiraService_Expecter) GetSprintReport(context1 interface{}, getSprintReportRequest interface{}) *JiraService_GetSprintReport_Call {
	return &JiraService_GetSprintReport_Call{Call: _e.mock.On("GetSprintReport", context1, getSprintReportRequest)}
}

func (_c *JiraService_GetSprintReport_Call) Run(run func(context1 context.Context, getSprintReportRequest models.GetSprintReportRequest)) *JiraService_GetSprintReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetSprintReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetSprintReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetSprintReport_Call) Return(sprintReport *models.SprintReport, err error) *JiraService_GetSprintReport_Call {
	_c.Call.Return(sprintReport, err)
	return _c
}

func (_c *JiraService_GetSprintReport_Call) RunAndReturn(run func(context1 context.Context, getSprintReportRequest models.GetSprintReportRequest) (*models.SprintReport, error)) *JiraService_GetSprintReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetSprintWorkloadReport provides a mock function for the type JiraService
func (_mock *JiraService) GetSprintWorkloadReport(context1 context.Context, getSprintWorkloadReportRequest models.GetSprintWorkloadReportRequest) (*models.SprintWorkloadReport, error) {
	ret := _mock.Called(context1, getSprintWorkloadReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetSprintWorkloadReport")
	}

	var r0 *models.SprintWorkloadReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintWorkloadReportRequest) (*models.SprintWorkloadReport, error)); ok {
		return returnFunc(context1, getSprintWorkloadReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSprintWorkloadReportRequest) *models.SprintWorkloadReport); ok {
		r0 = returnFunc(context1, getSprintWorkloadReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SprintWorkloadReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetSprintWorkloadReportRequest) error); ok {
		r1 = returnFunc(context1, getSprintWorkloadReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetSprintWorkloadReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSprintWorkloadReport'
type JiraService_GetSprintWorkloadReport_Call struct {
	*mock.Call
}

// GetSprintWorkloadReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getSprintWorkloadReportRequest models.GetSprintWorkloadReportRequest
func (_e *JiraService_Expecter) GetSprintWorkloadReport(context1 interface{}, getSprintWorkloadReportRequest interface{}) *JiraService_GetSprintWorkloadReport_Call {
	return &JiraService_GetSprintWorkloadReport_Call{Call: _e.mock.On("GetSprintWorkloadReport", context1, getSprintWorkloadReportRequest)}
}

func (_c *JiraService_GetSprintWorkloadReport_Call) Run(run func(context1 context.Context, getSprintWorkloadReportRequest models.GetSprintWorkloadReportRequest)) *JiraService_GetSprintWorkloadReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetSprintWorkloadReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetSprintWorkloadReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetSprintWorkloadReport_Call) Return(sprintWorkloadReport *models.SprintWorkloadReport, err error) *JiraService_GetSprintWorkloadReport_Call {
	_c.Call.Return(sprintWorkloadReport, err)
	return _c
}

func (_c *JiraService_GetSprintWorkloadReport_Call) RunAndReturn(run func(context1 context.Context, getSprintWorkloadReportRequest models.GetSprintWorkloadReportRequest) (*models.SprintWorkloadReport, error)) *JiraService_GetSprintWorkloadReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamWipSnapshot provides a mock function for the type JiraService
func (_mock *JiraService) GetTeamWipSnapshot(context1 context.Context, getTeamWipSnapshotRequest models.GetTeamWipSnapshotRequest) (*models.TeamWipSnapshot, error) {
	ret := _mock.Called(context1, getTeamWipSnapshotRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamWipSnapshot")
	}

	var r0 *models.TeamWipSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetTeamWipSnapshotRequest) (*models.TeamWipSnapshot, error)); ok {
		return returnFunc(context1, getTeamWipSnapshotRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetTeamWipSnapshotRequest) *models.TeamWipSnapshot); ok {
		r0 = returnFunc(context1, getTeamWipSnapshotRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamWipSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetTeamWipSnapshotRequest) error); ok {
		r1 = returnFunc(context1, getTeamWipSnapshotRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetTeamWipSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamWipSnapshot'
type JiraService_GetTeamWipSnapshot_Call struct {
	*mock.Call
}

// GetTeamWipSnapshot is a helper method to define mock.On call
//   - context1 context.Context
//   - getTeamWipSnapshotRequest models.GetTeamWipSnapshotRequest
func (_e *JiraService_Expecter) GetTeamWipSnapshot(context1 interface{}, getTeamWipSnapshotRequest interface{}) *JiraService_GetTeamWipSnapshot_Call {
	return &JiraService_GetTeamWipSnapshot_Call{Call: _e.mock.On("GetTeamWipSnapshot", context1, getTeamWipSnapshotRequest)}
}

func (_c *JiraService_GetTeamWipSnapshot_Call) Run(run func(context1 context.Context, getTeamWipSnapshotRequest models.GetTeamWipSnapshotRequest)) *JiraService_GetTeamWipSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetTeamWipSnapshotRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetTeamWipSnapshotRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetTeamWipSnapshot_Call) Return(teamWipSnapshot *models.TeamWipSnapshot, err error) *JiraService_GetTeamWipSnapshot_Call {
	_c.Call.Return(teamWipSnapshot, err)
	return _c
}

func (_c *JiraService_GetTeamWipSnapshot_Call) RunAndReturn(run func(context1 context.Context, getTeamWipSnapshotRequest models.GetTeamWipSnapshotRequest) (*models.TeamWipSnapshot, error)) *JiraService_GetTeamWipSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitions provides a mock function for the type JiraService
func (_mock *JiraService) GetTransitions(context1 context.Context, getTransitionsRequest models.GetTransitionsRequest) ([]models.Transition, error) {
	ret := _mock.Called(context1, getTransitionsRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitions")
	}

	var r0 []models.Transition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetTransitionsRequest) ([]models.Transition, error)); ok {
		return returnFunc(context1, getTransitionsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetTransitionsRequest) []models.Transition); ok {
		r0 = returnFunc(context1, getTransitionsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetTransitionsRequest) error); ok {
		r1 = returnFunc(context1, getTransitionsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetTransitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitions'
type JiraService_GetTransitions_Call struct {
	*mock.Call
}

// GetTransitions is a helper method to define mock.On call
//   - context1 context.Context
//   - getTransitionsRequest models.GetTransitionsRequest
func (_e *JiraService_Expecter) GetTransitions(context1 interface{}, getTransitionsRequest interface{}) *JiraService_GetTransitions_Call {
	return &JiraService_GetTransitions_Call{Call: _e.mock.On("GetTransitions", context1, getTransitionsRequest)}
}

func (_c *JiraService_GetTransitions_Call) Run(run func(context1 context.Context, getTransitionsRequest models.GetTransitionsRequest)) *JiraService_GetTransitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetTransitionsRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetTransitionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetTransitions_Call) Return(transitions []models.Transition, err error) *JiraService_GetTransitions_Call {
	_c.Call.Return(transitions, err)
	return _c
}

func (_c *JiraService_GetTransitions_Call) RunAndReturn(run func(context1 context.Context, getTransitionsRequest models.GetTransitionsRequest) ([]models.Transition, error)) *JiraService_GetTransitions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUtilizationReport provides a mock function for the type JiraService
func (_mock *JiraService) GetUtilizationReport(context1 context.Context, getUtilizationReportRequest models.GetUtilizationReportRequest) (*models.UtilizationReport, error) {
	ret := _mock.Called(context1, getUtilizationReportRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetUtilizationReport")
	}

	var r0 *models.UtilizationReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetUtilizationReportRequest) (*models.UtilizationReport, error)); ok {
		return returnFunc(context1, getUtilizationReportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetUtilizationReportRequest) *models.UtilizationReport); ok {
		r0 = returnFunc(context1, getUtilizationReportRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UtilizationReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetUtilizationReportRequest) error); ok {
		r1 = returnFunc(context1, getUtilizationReportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetUtilizationReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUtilizationReport'
type JiraService_GetUtilizationReport_Call struct {
	*mock.Call
}

// GetUtilizationReport is a helper method to define mock.On call
//   - context1 context.Context
//   - getUtilizationReportRequest models.GetUtilizationReportRequest
func (_e *JiraService_Expecter) GetUtilizationReport(context1 interface{}, getUtilizationReportRequest interface{}) *JiraService_GetUtilizationReport_Call {
	return &JiraService_GetUtilizationReport_Call{Call: _e.mock.On("GetUtilizationReport", context1, getUtilizationReportRequest)}
}

func (_c *JiraService_GetUtilizationReport_Call) Run(run func(context1 context.Context, getUtilizationReportRequest models.GetUtilizationReportRequest)) *JiraService_GetUtilizationReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetUtilizationReportRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetUtilizationReportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetUtilizationReport_Call) Return(utilizationReport *models.UtilizationReport, err error) *JiraService_GetUtilizationReport_Call {
	_c.Call.Return(utilizationReport, err)
	return _c
}

func (_c *JiraService_GetUtilizationReport_Call) RunAndReturn(run func(context1 context.Context, getUtilizationReportRequest models.GetUtilizationReportRequest) (*models.UtilizationReport, error)) *JiraService_GetUtilizationReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type JiraService
func (_mock *JiraService) GetVersion(context1 context.Context, getVersionRequest models.GetVersionRequest) (*models.Version, error) {
	ret := _mock.Called(context1, getVersionRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *models.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetVersionRequest) (*models.Version, error)); ok {
		return returnFunc(context1, getVersionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetVersionRequest) *models.Version); ok {
		r0 = returnFunc(context1, getVersionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Version)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetVersionRequest) error); ok {
		r1 = returnFunc(context1, getVersionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type JiraService_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - getVersionRequest models.GetVersionRequest
func (_e *JiraService_Expecter) GetVersion(context1 interface{}, getVersionRequest interface{}) *JiraService_GetVersion_Call {
	return &JiraService_GetVersion_Call{Call: _e.mock.On("GetVersion", context1, getVersionRequest)}
}

func (_c *JiraService_GetVersion_Call) Run(run func(context1 context.Context, getVersionRequest models.GetVersionRequest)) *JiraService_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetVersionRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetVersionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetVersion_Call) Return(version *models.Version, err error) *JiraService_GetVersion_Call {
	_c.Call.Return(version, err)
	return _c
}

func (_c *JiraService_GetVersion_Call) RunAndReturn(run func(context1 context.Context, getVersionRequest models.GetVersionRequest) (*models.Version, error)) *JiraService_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorklogs provides a mock function for the type JiraService
func (_mock *JiraService) GetWorklogs(context1 context.Context, getWorklogsRequest models.GetWorklogsRequest) (*models.WorklogList, error) {
	ret := _mock.Called(context1, getWorklogsRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetWorklogs")
	}

	var r0 *models.WorklogList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetWorklogsRequest) (*models.WorklogList, error)); ok {
		return returnFunc(context1, getWorklogsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetWorklogsRequest) *models.WorklogList); ok {
		r0 = returnFunc(context1, getWorklogsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WorklogList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetWorklogsRequest) error); ok {
		r1 = returnFunc(context1, getWorklogsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_GetWorklogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorklogs'
type JiraService_GetWorklogs_Call struct {
	*mock.Call
}

// GetWorklogs is a helper method to define mock.On call
//   - context1 context.Context
//   - getWorklogsRequest models.GetWorklogsRequest
func (_e *JiraService_Expecter) GetWorklogs(context1 interface{}, getWorklogsRequest interface{}) *JiraService_GetWorklogs_Call {
	return &JiraService_GetWorklogs_Call{Call: _e.mock.On("GetWorklogs", context1, getWorklogsRequest)}
}

func (_c *JiraService_GetWorklogs_Call) Run(run func(context1 context.Context, getWorklogsRequest models.GetWorklogsRequest)) *JiraService_GetWorklogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetWorklogsRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetWorklogsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_GetWorklogs_Call) Return(worklogList *models.WorklogList, err error) *JiraService_GetWorklogs_Call {
	_c.Call.Return(worklogList, err)
	return _c
}

func (_c *JiraService_GetWorklogs_Call) RunAndReturn(run func(context1 context.Context, getWorklogsRequest models.GetWorklogsRequest) (*models.WorklogList, error)) *JiraService_GetWorklogs_Call {
	_c.Call.Return(run)
	return _c
}

// LinkIssues provides a mock function for the type JiraService
func (_mock *JiraService) LinkIssues(context1 context.Context, linkIssuesRequest models.LinkIssuesRequest) (*models.IssueMutationResult, error) {
	ret := _mock.Called(context1, linkIssuesRequest)

	if len(ret) == 0 {
		panic("no return value specified for LinkIssues")
	}

	var r0 *models.IssueMutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LinkIssuesRequest) (*models.IssueMutationResult, error)); ok {
		return returnFunc(context1, linkIssuesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LinkIssuesRequest) *models.IssueMutationResult); ok {
		r0 = returnFunc(context1, linkIssuesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueMutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.LinkIssuesRequest) error); ok {
		r1 = returnFunc(context1, linkIssuesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_LinkIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkIssues'
type JiraService_LinkIssues_Call struct {
	*mock.Call
}

// LinkIssues is a helper method to define mock.On call
//   - context1 context.Context
//   - linkIssuesRequest models.LinkIssuesRequest
func (_e *JiraService_Expecter) LinkIssues(context1 interface{}, linkIssuesRequest interface{}) *JiraService_LinkIssues_Call {
	return &JiraService_LinkIssues_Call{Call: _e.mock.On("LinkIssues", context1, linkIssuesRequest)}
}

func (_c *JiraService_LinkIssues_Call) Run(run func(context1 context.Context, linkIssuesRequest models.LinkIssuesRequest)) *JiraService_LinkIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.LinkIssuesRequest
		if args[1] != nil {
			arg1 = args[1].(models.LinkIssuesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_LinkIssues_Call) Return(issueMutationResult *models.IssueMutationResult, err error) *JiraService_LinkIssues_Call {
	_c.Call.Return(issueMutationResult, err)
	return _c
}

func (_c *JiraService_LinkIssues_Call) RunAndReturn(run func(context1 context.Context, linkIssuesRequest models.LinkIssuesRequest) (*models.IssueMutationResult, error)) *JiraService_LinkIssues_Call {
	_c.Call.Return(run)
	return _c
}

// ListIssueTypes provides a mock function for the type JiraService
func (_mock *JiraService) ListIssueTypes(context1 context.Context, listIssueTypesRequest models.ListIssueTypesRequest) ([]models.IssueType, error) {
	ret := _mock.Called(context1, listIssueTypesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListIssueTypes")
	}

	var r0 []models.IssueType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListIssueTypesRequest) ([]models.IssueType, error)); ok {
		return returnFunc(context1, listIssueTypesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListIssueTypesRequest) []models.IssueType); ok {
		r0 = returnFunc(context1, listIssueTypesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IssueType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ListIssueTypesRequest) error); ok {
		r1 = returnFunc(context1, listIssueTypesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_ListIssueTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIssueTypes'
type JiraService_ListIssueTypes_Call struct {
	*mock.Call
}

// ListIssueTypes is a helper method to define mock.On call
//   - context1 context.Context
//   - listIssueTypesRequest models.ListIssueTypesRequest
func (_e *JiraService_Expecter) ListIssueTypes(context1 interface{}, listIssueTypesRequest interface{}) *JiraService_ListIssueTypes_Call {
	return &JiraService_ListIssueTypes_Call{Call: _e.mock.On("ListIssueTypes", context1, listIssueTypesRequest)}
}

func (_c *JiraService_ListIssueTypes_Call) Run(run func(context1 context.Context, listIssueTypesRequest models.ListIssueTypesRequest)) *JiraService_ListIssueTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ListIssueTypesRequest
		if args[1] != nil {
			arg1 = args[1].(models.ListIssueTypesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_ListIssueTypes_Call) Return(issueTypes []models.IssueType, err error) *JiraService_ListIssueTypes_Call {
	_c.Call.Return(issueTypes, err)
	return _c
}

func (_c *JiraService_ListIssueTypes_Call) RunAndReturn(run func(context1 context.Context, listIssueTypesRequest models.ListIssueTypesRequest) ([]models.IssueType, error)) *JiraService_ListIssueTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectVersions provides a mock function for the type JiraService
func (_mock *JiraService) ListProjectVersions(context1 context.Context, listProjectVersionsRequest models.ListProjectVersionsRequest) (*models.VersionCollection, error) {
	ret := _mock.Called(context1, listProjectVersionsRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectVersions")
	}

	var r0 *models.VersionCollection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListProjectVersionsRequest) (*models.VersionCollection, error)); ok {
		return returnFunc(context1, listProjectVersionsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListProjectVersionsRequest) *models.VersionCollection); ok {
		r0 = returnFunc(context1, listProjectVersionsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VersionCollection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ListProjectVersionsRequest) error); ok {
		r1 = returnFunc(context1, listProjectVersionsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_ListProjectVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectVersions'
type JiraService_ListProjectVersions_Call struct {
	*mock.Call
}

// ListProjectVersions is a helper method to define mock.On call
//   - context1 context.Context
//   - listProjectVersionsRequest models.ListProjectVersionsRequest
func (_e *JiraService_Expecter) ListProjectVersions(context1 interface{}, listProjectVersionsRequest interface{}) *JiraService_ListProjectVersions_Call {
	return &JiraService_ListProjectVersions_Call{Call: _e.mock.On("ListProjectVersions", context1, listProjectVersionsRequest)}
}

func (_c *JiraService_ListProjectVersions_Call) Run(run func(context1 context.Context, listProjectVersionsRequest models.ListProjectVersionsRequest)) *JiraService_ListProjectVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ListProjectVersionsRequest
		if args[1] != nil {
			arg1 = args[1].(models.ListProjectVersionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_ListProjectVersions_Call) Return(versionCollection *models.VersionCollection, err error) *JiraService_ListProjectVersions_Call {
	_c.Call.Return(versionCollection, err)
	return _c
}

func (_c *JiraService_ListProjectVersions_Call) RunAndReturn(run func(context1 context.Context, listProjectVersionsRequest models.ListProjectVersionsRequest) (*models.VersionCollection, error)) *JiraService_ListProjectVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListSprints provides a mock function for the type JiraService
func (_mock *JiraService) ListSprints(context1 context.Context, listSprintsRequest models.ListSprintsRequest) (*models.SprintCollection, error) {
	ret := _mock.Called(context1, listSprintsRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListSprints")
	}

	var r0 *models.SprintCollection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListSprintsRequest) (*models.SprintCollection, error)); ok {
		return returnFunc(context1, listSprintsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListSprintsRequest) *models.SprintCollection); ok {
		r0 = returnFunc(context1, listSprintsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SprintCollection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ListSprintsRequest) error); ok {
		r1 = returnFunc(context1, listSprintsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_ListSprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSprints'
type JiraService_ListSprints_Call struct {
	*mock.Call
}

// ListSprints is a helper method to define mock.On call
//   - context1 context.Context
//   - listSprintsRequest models.ListSprintsRequest
func (_e *JiraService_Expecter) ListSprints(context1 interface{}, listSprintsRequest interface{}) *JiraService_ListSprints_Call {
	return &JiraService_ListSprints_Call{Call: _e.mock.On("ListSprints", context1, listSprintsRequest)}
}

func (_c *JiraService_ListSprints_Call) Run(run func(context1 context.Context, listSprintsRequest models.ListSprintsRequest)) *JiraService_ListSprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ListSprintsRequest
		if args[1] != nil {
			arg1 = args[1].(models.ListSprintsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_ListSprints_Call) Return(sprintCollection *models.SprintCollection, err error) *JiraService_ListSprints_Call {
	_c.Call.Return(sprintCollection, err)
	return _c
}

func (_c *JiraService_ListSprints_Call) RunAndReturn(run func(context1 context.Context, listSprintsRequest models.ListSprintsRequest) (*models.SprintCollection, error)) *JiraService_ListSprints_Call {
	_c.Call.Return(run)
	return _c
}

// ListStatuses provides a mock function for the type JiraService
func (_mock *JiraService) ListStatuses(context1 context.Context, listStatusesRequest models.ListStatusesRequest) (*models.StatusCatalog, error) {
	ret := _mock.Called(context1, listStatusesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListStatuses")
	}

	var r0 *models.StatusCatalog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListStatusesRequest) (*models.StatusCatalog, error)); ok {
		return returnFunc(context1, listStatusesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListStatusesRequest) *models.StatusCatalog); ok {
		r0 = returnFunc(context1, listStatusesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StatusCatalog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ListStatusesRequest) error); ok {
		r1 = returnFunc(context1, listStatusesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_ListStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStatuses'
type JiraService_ListStatuses_Call struct {
	*mock.Call
}

// ListStatuses is a helper method to define mock.On call
//   - context1 context.Context
//   - listStatusesRequest models.ListStatusesRequest
func (_e *JiraService_Expecter) ListStatuses(context1 interface{}, listStatusesRequest interface{}) *JiraService_ListStatuses_Call {
	return &JiraService_ListStatuses_Call{Call: _e.mock.On("ListStatuses", context1, listStatusesRequest)}
}

func (_c *JiraService_ListStatuses_Call) Run(run func(context1 context.Context, listStatusesRequest models.ListStatusesRequest)) *JiraService_ListStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ListStatusesRequest
		if args[1] != nil {
			arg1 = args[1].(models.ListStatusesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_ListStatuses_Call) Return(statusCatalog *models.StatusCatalog, err error) *JiraService_ListStatuses_Call {
	_c.Call.Return(statusCatalog, err)
	return _c
}

func (_c *JiraService_ListStatuses_Call) RunAndReturn(run func(context1 context.Context, listStatusesRequest models.ListStatusesRequest) (*models.StatusCatalog, error)) *JiraService_ListStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// SearchIssues provides a mock function for the type JiraService
func (_mock *JiraService) SearchIssues(context1 context.Context, searchIssuesRequest models.SearchIssuesRequest) (*models.SearchIssuesResult, error) {
	ret := _mock.Called(context1, searchIssuesRequest)

	if len(ret) == 0 {
		panic("no return value specified for SearchIssues")
	}

	var r0 *models.SearchIssuesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SearchIssuesRequest) (*models.SearchIssuesResult, error)); ok {
		return returnFunc(context1, searchIssuesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SearchIssuesRequest) *models.SearchIssuesResult); ok {
		r0 = returnFunc(context1, searchIssuesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchIssuesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.SearchIssuesRequest) error); ok {
		r1 = returnFunc(context1, searchIssuesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_SearchIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchIssues'
type JiraService_SearchIssues_Call struct {
	*mock.Call
}

// SearchIssues is a helper method to define mock.On call
//   - context1 context.Context
//   - searchIssuesRequest models.SearchIssuesRequest
func (_e *JiraService_Expecter) SearchIssues(context1 interface{}, searchIssuesRequest interface{}) *JiraService_SearchIssues_Call {
	return &JiraService_SearchIssues_Call{Call: _e.mock.On("SearchIssues", context1, searchIssuesRequest)}
}

func (_c *JiraService_SearchIssues_Call) Run(run func(context1 context.Context, searchIssuesRequest models.SearchIssuesRequest)) *JiraService_SearchIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SearchIssuesRequest
		if args[1] != nil {
			arg1 = args[1].(models.SearchIssuesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_SearchIssues_Call) Return(searchIssuesResult *models.SearchIssuesResult, err error) *JiraService_SearchIssues_Call {
	_c.Call.Return(searchIssuesResult, err)
	return _c
}

func (_c *JiraService_SearchIssues_Call) RunAndReturn(run func(context1 context.Context, searchIssuesRequest models.SearchIssuesRequest) (*models.SearchIssuesResult, error)) *JiraService_SearchIssues_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSprints provides a mock function for the type JiraService
func (_mock *JiraService) SearchSprints(context1 context.Context, searchSprintsRequest models.SearchSprintsRequest) (*models.SprintCollection, error) {
	ret := _mock.Called(context1, searchSprintsRequest)

	if len(ret) == 0 {
		panic("no return value specified for SearchSprints")
	}

	var r0 *models.SprintCollection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SearchSprintsRequest) (*models.SprintCollection, error)); ok {
		return returnFunc(context1, searchSprintsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SearchSprintsRequest) *models.SprintCollection); ok {
		r0 = returnFunc(context1, searchSprintsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SprintCollection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.SearchSprintsRequest) error); ok {
		r1 = returnFunc(context1, searchSprintsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_SearchSprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSprints'
type JiraService_SearchSprints_Call struct {
	*mock.Call
}

// SearchSprints is a helper method to define mock.On call
//   - context1 context.Context
//   - searchSprintsRequest models.SearchSprintsRequest
func (_e *JiraService_Expecter) SearchSprints(context1 interface{}, searchSprintsRequest interface{}) *JiraService_SearchSprints_Call {
	return &JiraService_SearchSprints_Call{Call: _e.mock.On("SearchSprints", context1, searchSprintsRequest)}
}

func (_c *JiraService_SearchSprints_Call) Run(run func(context1 context.Context, searchSprintsRequest models.SearchSprintsRequest)) *JiraService_SearchSprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SearchSprintsRequest
		if args[1] != nil {
			arg1 = args[1].(models.SearchSprintsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_SearchSprints_Call) Return(sprintCollection *models.SprintCollection, err error) *JiraService_SearchSprints_Call {
	_c.Call.Return(sprintCollection, err)
	return _c
}

func (_c *JiraService_SearchSprints_Call) RunAndReturn(run func(context1 context.Context, searchSprintsRequest models.SearchSprintsRequest) (*models.SprintCollection, error)) *JiraService_SearchSprints_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionIssue provides a mock function for the type JiraService
func (_mock *JiraService) TransitionIssue(context1 context.Context, transitionIssueRequest models.TransitionIssueRequest) (*models.IssueMutationResult, error) {
	ret := _mock.Called(context1, transitionIssueRequest)

	if len(ret) == 0 {
		panic("no return value specified for TransitionIssue")
	}

	var r0 *models.IssueMutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TransitionIssueRequest) (*models.IssueMutationResult, error)); ok {
		return returnFunc(context1, transitionIssueRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TransitionIssueRequest) *models.IssueMutationResult); ok {
		r0 = returnFunc(context1, transitionIssueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueMutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.TransitionIssueRequest) error); ok {
		r1 = returnFunc(context1, transitionIssueRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_TransitionIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionIssue'
type JiraService_TransitionIssue_Call struct {
	*mock.Call
}

// TransitionIssue is a helper method to define mock.On call
//   - context1 context.Context
//   - transitionIssueRequest models.TransitionIssueRequest
func (_e *JiraService_Expecter) TransitionIssue(context1 interface{}, transitionIssueRequest interface{}) *JiraService_TransitionIssue_Call {
	return &JiraService_TransitionIssue_Call{Call: _e.mock.On("TransitionIssue", context1, transitionIssueRequest)}
}

func (_c *JiraService_TransitionIssue_Call) Run(run func(context1 context.Context, transitionIssueRequest models.TransitionIssueRequest)) *JiraService_TransitionIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.TransitionIssueRequest
		if args[1] != nil {
			arg1 = args[1].(models.TransitionIssueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_TransitionIssue_Call) Return(issueMutationResult *models.IssueMutationResult, err error) *JiraService_TransitionIssue_Call {
	_c.Call.Return(issueMutationResult, err)
	return _c
}

func (_c *JiraService_TransitionIssue_Call) RunAndReturn(run func(context1 context.Context, transitionIssueRequest models.TransitionIssueRequest) (*models.IssueMutationResult, error)) *JiraService_TransitionIssue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIssue provides a mock function for the type JiraService
func (_mock *JiraService) UpdateIssue(context1 context.Context, updateIssueRequest models.UpdateIssueRequest) (*models.IssueMutationResult, error) {
	ret := _mock.Called(context1, updateIssueRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssue")
	}

	var r0 *models.IssueMutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UpdateIssueRequest) (*models.IssueMutationResult, error)); ok {
		return returnFunc(context1, updateIssueRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UpdateIssueRequest) *models.IssueMutationResult); ok {
		r0 = returnFunc(context1, updateIssueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IssueMutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UpdateIssueRequest) error); ok {
		r1 = returnFunc(context1, updateIssueRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraService_UpdateIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIssue'
type JiraService_UpdateIssue_Call struct {
	*mock.Call
}

// UpdateIssue is a helper method to define mock.On call
//   - context1 context.Context
//   - updateIssueRequest models.UpdateIssueRequest
func (_e *JiraService_Expecter) UpdateIssue(context1 interface{}, updateIssueRequest interface{}) *JiraService_UpdateIssue_Call {
	return &JiraService_UpdateIssue_Call{Call: _e.mock.On("UpdateIssue", context1, updateIssueRequest)}
}

func (_c *JiraService_UpdateIssue_Call) Run(run func(context1 context.Context, updateIssueRequest models.UpdateIssueRequest)) *JiraService_UpdateIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UpdateIssueRequest
		if args[1] != nil {
			arg1 = args[1].(models.UpdateIssueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JiraService_UpdateIssue_Call) Return(issueMutationResult *models.IssueMutationResult, err error) *JiraService_UpdateIssue_Call {
	_c.Call.Return(issueMutationResult, err)
	return _c
}

func (_c *JiraService_UpdateIssue_Call) RunAndReturn(run func(context1 context.Context, updateIssueRequest models.UpdateIssueRequest) (*models.IssueMutationResult, error)) *JiraService_UpdateIssue_Call {
	_c.Call.Return(run)
	return _c
}
